uclouvain/osis-portal-dissertation

fixtures/message_templates_dissertation.json, forms.py, locale/en/LC_MESSAGES/django.po, locale/fr_BE/LC_MESSAGES/django.po, models/dissertation.py, models/dissertation_update.py, templates/dissertation_detail.html, tests/models/test_dissertation.py, tests/views/test_dissertation.py, urls.py, views/dissertation.py
=> Od 44 Fonction go back pour remettre un memoire en dir_submit en draft

locale/en/LC_MESSAGES/django.po, locale/fr_BE/LC_MESSAGES/django.po
=> OD-44 correction erreurs de traductions.

templates/dissertation_detail.html
=> OD-44 correction erreur de traduction

forms.py, models/dissertation.py, templates/dissertation_form.html, templates/proposition_dissertation_detail.html, urls.py, views/dissertation.py
=> OD-54 creating Dissertation from a subject

locale/en/LC_MESSAGES/django.po, locale/fr_BE/LC_MESSAGES/django.po
=> OD-54 correction traduction

locale/en/LC_MESSAGES/django.po, locale/fr_BE/LC_MESSAGES/django.po, templates/dissertation_detail.html, templates/dissertationdocumentfile_confirm_delete_inner.html, tests/factories/dissertation_document_file.py, tests/views/test_upload_dissertation_file.py, urls.py, views/upload_dissertation_file.py
=> Od 78 modification de l'ajout, suppression du pdf côté portal.

templates/dissertation_detail.html
=> OD-78 suppression d'un bouton dans le template

locale/fr_BE/LC_MESSAGES/django.po, models/dissertation.py, models/enums/defend_periode_choices.py, templates/dissertation_detail.html, tests/factories/dissertation.py, views/dissertation.py
=> OD-64 correction erreur de traduction

locale/en/LC_MESSAGES/django.po, locale/fr_BE/LC_MESSAGES/django.po, templates/dissertation_detail.html
=> OD-65 disabled submission if there is already one submitted

tests/factories/dissertation.py, tests/models/test_dissertation.py
=> OD-64 correction d'erreur de test

locale/en/LC_MESSAGES/django.po, locale/fr_BE/LC_MESSAGES/django.po, models/enums/dissertation_role_status.py, views/dissertation.py, views/upload_dissertation_file.py
=> OD-81 Dissertation update for upload and delete file

templates/dissertations_list.html
=> OD-86 add alert-danger

views/dissertation.py
=> OD-87 ajout de clé de traduction de justification a exclure

.codeclimate.yml, .travis.yml, setup.cfg
NE PAS MERGER. Il faut remplacer le CC_TEST_REPORTER_ID par celui du repo.
=> Added travis and codeclimate configurations

models/dissertation.py, views/dissertation.py, views/proposition_dissertation.py
=> [OSIS-3369] Modify current academic year query

views/proposition_dissertation.py
=> OD-99 Use starting_anac instead of current_anac !

models/adviser.py, models/dissertation.py, models/dissertation_document_file.py, models/dissertation_role.py, models/proposition_document_file.py, models/proposition_offer.py, models/proposition_role.py, views/dissertation.py, views/proposition_dissertation.py, views/upload_dissertation_file.py, views/upload_proposition_file.py
=> Remove useless

locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-3708 replace "éditer" by "modifier"

models/dissertation.py
=> OSIS-5564 removed unused import to 'offer_year'

templates/dissertation.html
=> Fontawesome

views/dissertation.py
=> [Master] Fixed view dissertation_new quand il y a pas de pk

locale/en/LC_MESSAGES/django.po, locale/fr_BE/LC_MESSAGES/django.po, views/dissertation.py
=> Fixed import

forms.py
=> FIxed form update title

requirements.txt
=> OSIS-7894 Change requirement.txt

requirements.txt
=> [TEST] Release

templates/dissertation_detail.html, templates/dissertation_reader_edit_inner.html, templates/proposition_dissertation_detail.html
=> [WIP] Remove .media

requirements.txt, templates/dissertation_detail.html, templates/dissertation_reader_edit_inner.html, templates/proposition_dissertation_detail.html, tests/factories/adviser.py, tests/factories/dissertation.py, tests/factories/dissertation_document_file.py, tests/factories/dissertation_location.py, tests/factories/dissertation_role.py, tests/factories/offer_proposition.py, tests/factories/offer_proposition_group.py, tests/factories/proposition_dissertation.py, tests/factories/proposition_offer.py
=> [To QA] Release

requirements.txt, templates/dissertation_detail.html, templates/dissertation_reader_edit_inner.html, templates/proposition_dissertation_detail.html, tests/factories/adviser.py, tests/factories/dissertation.py, tests/factories/dissertation_document_file.py, tests/factories/dissertation_location.py, tests/factories/dissertation_role.py, tests/factories/offer_proposition.py, tests/factories/offer_proposition_group.py, tests/factories/proposition_dissertation.py, tests/factories/proposition_offer.py
=> [To TEST] Release

templates/dissertation.html, templates/dissertation_add_justification.html, templates/dissertation_detail.html, templates/dissertation_edit_form.html, templates/dissertation_form.html, templates/dissertation_history.html, templates/dissertation_reader_edit_inner.html, templates/dissertation_title_form.html, templates/dissertations_list.html, templates/file_upload_modal.html, templates/modal.html, templates/proposition_dissertation_detail.html, templates/proposition_dissertations_list.html
=> [OSIS-9160] Mig BS5 - osis-dissertation

__init__.py, urls.py
=> [WIP] Python migration

locale/en/LC_MESSAGES/django.po, locale/fr_BE/LC_MESSAGES/django.po, templates/dissertation_detail.html
Pull request automatique pour la release de master
=> Release qa => master
